"""
Run the ORIGINAL coder-retry and evaluator prompts against the LLM.

Prompts are loaded verbatim from:
  - backend/factors/coder/qa_prompts.yaml  (qa_*)
  - backend/factors/coder/prompts.yaml     (base)

Mapping:
  coder_retry          qa_prompts.yaml : evolving_strategy_factor_implementation_v1_system
                                         + evolving_strategy_factor_implementation_v2_user
                       + JSON_ONLY_SUFFIX (copied verbatim from
                       backend/factors/coder/evolving_strategy.py:502)
  coder_error_summary  prompts.yaml    : evolving_strategy_error_summary_v2_system / _user
  code_feedback        qa_prompts.yaml : evaluator_code_feedback_v1_system / _user
  output_format        prompts.yaml    : evaluator_output_format_system
                       (user prompt is a literal df.info() string — see
                       eva_utils.py:253)
  final_decision       prompts.yaml    : evaluator_final_decision_v1_system / _user

All variable values come from `fixtures.py`. Edit the "── EDIT ──" sections
there to change what the LLM sees; do not edit this file.
"""

from __future__ import annotations

from jinja2 import Environment, StrictUndefined

from .common import load_yaml, run_case, PROMPT_PATHS
from . import fixtures as fx


_QA_YAML: dict | None = None
_BASE_YAML: dict | None = None


def _qa() -> dict:
    global _QA_YAML
    if _QA_YAML is None:
        _QA_YAML = load_yaml(PROMPT_PATHS["factors_coder_qa"])
    return _QA_YAML


def _base() -> dict:
    global _BASE_YAML
    if _BASE_YAML is None:
        _BASE_YAML = load_yaml(PROMPT_PATHS["factors_coder_base"])
    return _BASE_YAML


def _jinja(template: str, **vars) -> str:
    return Environment(undefined=StrictUndefined).from_string(template).render(**vars)


# Copied verbatim from backend/factors/coder/evolving_strategy.py:502
JSON_ONLY_SUFFIX = (
    "\n\nOUTPUT INSTRUCTION: Respond with ONLY the raw JSON object "
    "on a single line. No explanation, no preamble, no analysis. "
    'Example: {"expr": "TS_STD($close, 20)"}'
)


# ═════════════════════════════════════════════════════════════════════════
# Coder retry — FactorParsingStrategy.implement_one_task
#   (backend/factors/coder/evolving_strategy.py:411)
# Required Jinja vars:
#   system: scenario
#   user:   factor_information_str, former_expression, former_feedback,
#           queried_similar_error_knowledge, error_summary_critics,
#           similar_successful_factor_description, similar_successful_expression,
#           latest_attempt_to_latest_successful_execution
# ═════════════════════════════════════════════════════════════════════════

def test_coder_retry():
    y = _qa()
    scenario_desc = fx.SCENARIO.get_scenario_all_desc(filtered_tag="feature")

    system_prompt = _jinja(
        y["evolving_strategy_factor_implementation_v1_system"],
        scenario=scenario_desc,
    )
    user_prompt = _jinja(
        y["evolving_strategy_factor_implementation_v2_user"],
        factor_information_str=fx.FACTOR_TASK.get_task_description(),
        former_expression=fx.FORMER_EXPRESSION,
        former_feedback=fx.FORMER_FEEDBACK,
        queried_similar_error_knowledge=[],
        error_summary_critics=None,
        similar_successful_factor_description=None,
        similar_successful_expression=None,
        latest_attempt_to_latest_successful_execution=None,
    )
    user_prompt = user_prompt + JSON_ONLY_SUFFIX

    return run_case(
        group="coder_evaluator", case="coder_retry",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=True,
        expected_keys=["expr"],
    )


# ═════════════════════════════════════════════════════════════════════════
# Error summary — FactorParsingStrategy.error_summary
#   (backend/factors/coder/evolving_strategy.py:318)
# Required Jinja vars:
#   system: scenario, factor_information_str, code_and_feedback
#   user:   queried_similar_error_knowledge
# ═════════════════════════════════════════════════════════════════════════

def test_coder_error_summary():
    y = _base()
    scenario_desc = fx.SCENARIO.get_scenario_all_desc()

    system_prompt = _jinja(
        y["evolving_strategy_error_summary_v2_system"],
        scenario=scenario_desc,
        factor_information_str=fx.FACTOR_TASK.get_task_information(),
        code_and_feedback=(
            "=====Code=====\n"
            f"{fx.FACTOR_CODE}\n"
            "=====Feedback=====\n"
            f"{fx.EXECUTION_FEEDBACK_FAIL}"
        ),
    )
    user_prompt = _jinja(
        y["evolving_strategy_error_summary_v2_user"],
        queried_similar_error_knowledge=[],
    )
    # Backend allows empty queried_similar_error_knowledge; template then
    # produces an empty body. Fall back to a short cue so the LLM has context.
    if not user_prompt.strip():
        user_prompt = (
            "Refer to the system prompt above. Produce critics that address the "
            "root cause of the failure. No code — short bullets only."
        )

    return run_case(
        group="coder_evaluator", case="coder_error_summary",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=False,
    )


# ═════════════════════════════════════════════════════════════════════════
# Code feedback — FactorCodeEvaluator.evaluate (backend/factors/coder/eva_utils.py:131)
# Required Jinja vars:
#   system: scenario
#   user:   factor_information, code, execution_feedback, value_feedback, gt_code
# ═════════════════════════════════════════════════════════════════════════

def test_code_feedback():
    y = _qa()
    scenario_desc = fx.SCENARIO.get_scenario_all_desc(filtered_tag="feature")

    system_prompt = _jinja(
        y["evaluator_code_feedback_v1_system"],
        scenario=scenario_desc,
    )
    user_prompt = _jinja(
        y["evaluator_code_feedback_v1_user"],
        factor_information=fx.FACTOR_TASK.get_task_information(),
        code=fx.FACTOR_CODE,
        execution_feedback=fx.EXECUTION_FEEDBACK_OK,
        value_feedback=fx.VALUE_FEEDBACK,
        gt_code=None,
    )

    return run_case(
        group="coder_evaluator", case="code_feedback",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=False,
    )


# ═════════════════════════════════════════════════════════════════════════
# Output format — FactorOutputFormatEvaluator.evaluate
#   (backend/factors/coder/eva_utils.py:239)
# Required Jinja vars:
#   system: scenario
#   user:   (literal string built from gen_df.info() — see eva_utils.py:253)
# ═════════════════════════════════════════════════════════════════════════

def test_output_format():
    y = _base()
    scenario_desc = fx.SCENARIO.get_scenario_all_desc(filtered_tag="feature")

    system_prompt = _jinja(
        y["evaluator_output_format_system"],
        scenario=scenario_desc,
    )
    user_prompt = fx.OUTPUT_DF_INFO_STR   # literal, same shape as production

    return run_case(
        group="coder_evaluator", case="output_format",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=True,
        expected_keys=["output_format_decision", "output_format_feedback"],
    )


# ═════════════════════════════════════════════════════════════════════════
# Final decision — FactorFinalDecisionEvaluator.evaluate
#   (backend/factors/coder/eva_utils.py:560)
# Required Jinja vars:
#   system: scenario
#   user:   factor_information, execution_feedback, code_feedback, value_feedback
# ═════════════════════════════════════════════════════════════════════════

def test_final_decision():
    y = _base()
    scenario_desc = fx.SCENARIO.get_scenario_all_desc(filtered_tag="feature")

    system_prompt = _jinja(
        y["evaluator_final_decision_v1_system"],
        scenario=scenario_desc,
    )
    user_prompt = _jinja(
        y["evaluator_final_decision_v1_user"],
        factor_information=fx.FACTOR_TASK.get_task_information(),
        execution_feedback=fx.EXECUTION_FEEDBACK_OK,
        code_feedback=(
            "comment 1: Expression matches description.\n"
            "comment 2: Consider a longer window for stability."
        ),
        value_feedback=fx.VALUE_FEEDBACK,
    )

    return run_case(
        group="coder_evaluator", case="final_decision",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=True,
        expected_keys=["final_decision", "final_feedback"],
    )


CASES = {
    "coder_retry": test_coder_retry,
    "coder_error_summary": test_coder_error_summary,
    "code_feedback": test_code_feedback,
    "output_format": test_output_format,
    "final_decision": test_final_decision,
}
