"""
Run the ORIGINAL planning & evolution prompts against the LLM.

Prompts are loaded verbatim from:
  - backend/pipeline/prompts/planning_prompts.yaml
  - backend/pipeline/prompts/evolution_prompts.yaml

They use Python `.format()` style — all `{name}` placeholders are filled
from values in `fixtures.py`. To change what the LLM sees, edit the
"── EDIT ──" sections in `fixtures.py`; do not edit this file.
"""

from __future__ import annotations

from .common import load_yaml, render_format, run_case, PROMPT_PATHS
from . import fixtures as fx


_PLANNING_YAML: dict | None = None
_EVOLUTION_YAML: dict | None = None


def _planning() -> dict:
    global _PLANNING_YAML
    if _PLANNING_YAML is None:
        _PLANNING_YAML = load_yaml(PROMPT_PATHS["planning"])
    return _PLANNING_YAML


def _evolution() -> dict:
    global _EVOLUTION_YAML
    if _EVOLUTION_YAML is None:
        _EVOLUTION_YAML = load_yaml(PROMPT_PATHS["evolution"])
    return _EVOLUTION_YAML


# ═════════════════════════════════════════════════════════════════════════
# Planning — generate_parallel_directions (backend/pipeline/planning.py:148)
# Variables expected by user prompt: initial_direction, n
# ═════════════════════════════════════════════════════════════════════════

def test_planning():
    y = _planning()
    system_prompt = y["system"]
    user_prompt = render_format(
        y["user"],
        initial_direction=fx.PLANNING_INITIAL_DIRECTION,
        n=fx.PLANNING_NUM_DIRECTIONS,
    )
    return run_case(
        group="planning_evolution", case="planning",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=True,
        expected_keys=["directions"],
    )


# ═════════════════════════════════════════════════════════════════════════
# Mutation — detailed user prompt (backend/pipeline/evolution/mutation.py:190)
# Variables: parent_hypothesis, parent_factors, parent_metrics, parent_feedback
# ═════════════════════════════════════════════════════════════════════════

def test_mutation_detailed():
    y = _evolution()["mutation"]
    system_prompt = y["system"]
    user_prompt = render_format(
        y["user"],
        parent_hypothesis=fx.PARENT_HYPOTHESIS,
        parent_factors=fx.PARENT_FACTORS_STR,
        parent_metrics=fx.PARENT_METRICS_STR,
        parent_feedback=fx.PARENT_FEEDBACK_STR,
    )
    return run_case(
        group="planning_evolution", case="mutation_detailed",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=True,
        expected_keys=[
            "new_hypothesis", "exploration_direction",
            "orthogonality_reason", "expected_characteristics",
        ],
    )


# ═════════════════════════════════════════════════════════════════════════
# Mutation — simple user prompt. Variables: parent_hypothesis, parent_factors.
# Output: free-form text (new hypothesis). No JSON schema.
# ═════════════════════════════════════════════════════════════════════════

def test_mutation_simple():
    y = _evolution()["mutation"]
    system_prompt = y["system"]
    user_prompt = render_format(
        y["simple_user"],
        parent_hypothesis=fx.PARENT_HYPOTHESIS,
        parent_factors=fx.PARENT_FACTORS_STR,
    )
    return run_case(
        group="planning_evolution", case="mutation_simple",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=False,
    )


# ═════════════════════════════════════════════════════════════════════════
# Crossover — detailed user (backend/pipeline/evolution/crossover.py:225)
# Variables: parent_summaries
# ═════════════════════════════════════════════════════════════════════════

def test_crossover_detailed():
    y = _evolution()["crossover"]
    system_prompt = y["system"]
    user_prompt = render_format(
        y["user"],
        parent_summaries=fx.PARENT_SUMMARIES_STR,
    )
    return run_case(
        group="planning_evolution", case="crossover_detailed",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=True,
        expected_keys=[
            "hybrid_hypothesis", "fusion_logic",
            "innovation_points", "expected_benefits",
        ],
    )


# Crossover — simple user. Output: free-form text.

def test_crossover_simple():
    y = _evolution()["crossover"]
    system_prompt = y["system"]
    user_prompt = render_format(
        y["simple_user"],
        parent_summaries=fx.PARENT_SUMMARIES_STR,
    )
    return run_case(
        group="planning_evolution", case="crossover_simple",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        json_mode=False,
    )


CASES = {
    "planning": test_planning,
    "mutation_detailed": test_mutation_detailed,
    "mutation_simple": test_mutation_simple,
    "crossover_detailed": test_crossover_detailed,
    "crossover_simple": test_crossover_simple,
}
